// swift-tools-version: 5.9

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "This Side",
    platforms: [
        .iOS("17.5")
    ],
    products: [
        .iOSApplication(
            name: "This Side",
            targets: ["AppModule"],
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            capabilities: [
                .contacts(purposeString: "Friends Messageing"),
                .locationAlwaysAndWhenInUse(purposeString: "It’s a sneaky location-tracking app."),
                .appTransportSecurity(configuration: .init(
                    exceptionDomains: [
                        .init(
                            domainName: "To use GPS to track down your friend’s location, your system will need internet connectivity.",
                            includesSubdomains: true,
                            exceptionAllowsInsecureHTTPLoads: true
                        )
                    ]
                )),
                .motion(purposeString: "if you’re within a 100-meter radius, you’ll get a notification!"),
                .locationWhenInUse(purposeString: "Locations"),
                .nearbyInteractionAllowOnce(purposeString: "To reach out to a friend in a pinch (SOS)"),
                .incomingNetworkConnections(),
                .outgoingNetworkConnections()
            ],
            appCategory: "public.app-category.navigation"
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                .enableUpcomingFeature("BareSlashRegexLiterals")
            ]
        )
    ]
)
